version: "2"

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=test_pwd
      - POSTGRES_USER=link_aggregator
    ports:
      - 5432:5432

  bot:
    image: link_aggregator
    build: .
    ports: 
    - 8443:8443 
    restart: on-failure
    env_file:
      - .config
