version: "2"

services: 
  mongo:
    image: "mongo:3.6.2"
    volumes: 
    - mongo_data:/data/db
    ports:
    - 27017:27017

  bot:
    image: link_aggregator
    build: .
    ports: 
    - 8443:8443 
    restart: on-failure

volumes: 
  mongo_data:
